/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_goldingmedia_jni_GPIOUsbPower */

#ifndef _Included_com_goldingmedia_jni_GPIOUsbPower
#define _Included_com_goldingmedia_jni_GPIOUsbPower
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_goldingmedia_jni_GPIOUsbPower
 * Method:    usbPowerOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_goldingmedia_jni_GPIOUsbPower_usbPowerOn
  (JNIEnv *, jclass);

/*
 * Class:     com_goldingmedia_jni_GPIOUsbPower
 * Method:    usbPowerOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_goldingmedia_jni_GPIOUsbPower_usbPowerOff
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
